// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbahbdkldtdikcnjciew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJiYWhiZGtsZHRkaWtjbmpjaWV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNzE0MjksImV4cCI6MjA3MTY0NzQyOX0.em18DPFpWuU3sXY4gvtXo8CtXVxetNZQVKIMUNswu1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});